<a href="https://colab.research.google.com/github/cheronoF/Data-Science/blob/main/1Copy_of_Copy_of_Python_Programming_Simple_Random_Sampling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<font color="green">To start working on this notebook, or any other notebook that we will use in the Moringa Data Science Course, we will need to save our own copy of it. We can do this by clicking File > Save a Copy in Drive. We will then be able to make edits to our own copy of this notebook.</font>

# Python Programming:  Simple Random Sampling


## Importing our Libraries

In [ ]:
# importing numpy
import numpy as np

# importing pandas
import pandas as pd

# importing random module
# we will use random.sample() function to return a k length 
# list of unique elements chosen from our population
import random

## 1.0 Selecting More than One item from a List

In [ ]:
# Example 1
# ---
# Selecting more than one item from a list 
# ---
#

list = [20, 40, 80, 100, 120]
print ("Choosing 3 random items from a list using sample function", random.sample(list, k=3))

list = [20, 40, 20, 20, 20]
print ("Choosing 3 random items from a list using sample function",random.sample(list, k=2))

# As you can see we pass k=3 to choose 3 random elements from a list. 
# In return, we got a list of 3 random items.

Choosing 3 random items from a list using sample function [100, 40, 20]
Choosing 3 random items from a list using sample function [20, 20]


### <font color="green"> 1.0 Challenges</font>

In [ ]:
# Challenge 1
# ---
# Question: Create a list containing 10 counties in Kenya 
# then select 2 random counties from the list.


list = ["Uasin Gingu", "Machakos", "Kiambu", "Kakamega", "Kwale", "Lamu", "Bomet", "Laikipia", "Baringo", "Nandi"]
print (random.sample(list, k=2))

['Laikipia', 'Machakos']


In [ ]:
list = [ 1, 2, 3, 5, 7, 8 , 9]
random.sample(list, k=3)

[5, 1, 7]

## 2.0  Selecting the Random Sample from Dictionary

In [ ]:
# Example 1
# ---
# We can select a random key-value pair from the dictionary as shown 
# ---
#
marks_dict = {
  "Kelly": 55,
  "jhon": 70,
  "Donald": 60,
  "Lennin" :50
}

print ("Choosing 2 random items from a dictionary using sample method ", random.sample(marks_dict.items(), k=2))

Choosing 2 random items from a dictionary using sample method  [('Donald', 60), ('Kelly', 55)]


### <font color="green">2.0 Challenges</font>

In [ ]:
# Challenge 1
# ---
# A caterer offers three different food packages; 
# bronze package: starch:rice stew:chicken curry vegetable:cabbages desert:melon
# silver package: starch:rice and chappati  stew:beef curry vegetable:spinach desert:melon and bananas
# gold package: starch:rice, chappati and mukimo stew: beef curry vegetable:spinach and managu desert: tart
# Create a dictionary that stores the above information and select a sample of size 2 
# ---
#

food_packages = { 'Bronze Package': {'Starch': 'Rice Stew', 'Stew': 'Chicken Curry', 'Vegetable': ' Cabbages', 'Desert': 'Melon'},
                'Silver Package': {'Starch': 'Rice and Chapati', 'Stew': 'Beef Curry', 'Vegetable': 'Spinach', 'Desert': 'Melon and Bananas'},
                 'Gold Package': {'Starch': 'Rice, Chapati & Mukimo', 'Stew':'Beef Curry', 'Vegetable':'Spinach and Managu', 'Desert':'Tart'}}

random.sample(food_packages.items(), k=2)

[('Silver Package',
  {'Desert': 'Melon and Bananas',
   'Starch': 'Rice and Chapati',
   'Stew': 'Beef Curry',
   'Vegetable': 'Spinach'}),
 ('Gold Package',
  {'Desert': 'Tart',
   'Starch': 'Rice, Chapati & Mukimo',
   'Stew': 'Beef Curry',
   'Vegetable': 'Spinach and Managu'})]

## 3.0 Selecting a Random Sample with Replacement to including repetition


In [ ]:
# Example 1
# ---
# We can select a random sample with replacement to include repetition as shown below

names = ["Roger", "Nadal", "Novac", "Andre", "Sarena", "Mariya", "Martina"]

print("random sample with replacement to including repetition ", random.choices(names, k=3))

random sample with replacement to including repetition  ['Roger', 'Martina', 'Andre']


### <font color="green">3.0 Challenges</font>

In [ ]:
# Challenge 1
# ---
# Question: Select a random sample of 3 with replacement to include replacement from the 
# following list of months
# ---
#

months = ['January', 'February', 'March', 'April', 'May', 'June', 'July',
          'August', 'September', 'October', 'November', 'December']

print("random sample with replacement to including repetition ", random.choices(months, k=3))

random sample with replacement to including repetition  ['November', 'March', 'October']


## 4.0 Selecting a Random Sample from a Range of Integers

In [ ]:
# Example 1
# ---
# We can select a random sample from a range of integers as shown below
# ---
# 

weight_set = {40, 50, 55, 65, 75, 80}

print ("Choosing 4 random items from a set ", random.sample(weight_set, k=4))

Choosing 4 random items from a set  [55, 80, 75, 40]


### <font color="green">4.1 Challenges</font>

In [ ]:
# Challenge 1
# ---
# Question: Select a random sample from a range of integers as shown below
# --- 
# 
weight_set = {4, 5, 6, 7, 8, 9, 10}

random.sample(weight_set, k=2)

[5, 9]

## 5.0 Selecting a Sample Array from a Large multidimensional Array



In [ ]:
# Example 1
# ---
# We can select a sample array from a large multidimensional array as shown
# ---
# 

array = np.array([[2 ,4, 6], [5, 10, 15], [6, 12, 18], [7, 14, 21], [8, 16, 24]]) 
print("Printing 2D Array")
print(array)

# selecting multiple random rows from the 2D as shown
print("Selecting multiple random rows from the 2D array")
randomRows = np.random.randint(5, size=2)
for i in randomRows:
  print(array[i,:])

Printing 2D Array
[[ 2  4  6]
 [ 5 10 15]
 [ 6 12 18]
 [ 7 14 21]
 [ 8 16 24]]
Selecting multiple random rows from the 2D array
[ 7 14 21]
[ 5 10 15]


### <font color="green">5.0 Challenges</font>

In [ ]:
# Challenge 1
# ---
# Question: Select two arrays from the given multidimensional array
# ---
# 

a = np.array([[2, 4, 6, 8, 10], [3, 6, 9, 12, 15], [4, 8, 12, 16, 20], [1 ,2 , 4, 5, 6], [5, 10, 15, 20, 25], [6, 12, 18, 24, 30], [7, 14, 21, 28, 35]])

print("Printing 2D Array")
print(a)


Printing 2D Array
[[ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 1  2  4  5  6]
 [ 5 10 15 20 25]
 [ 6 12 18 24 30]
 [ 7 14 21 28 35]]


In [ ]:
# selecting multiple random rows from the 2D as shown
print("Selecting two arrays from the 2D array")
randomRows = np.random.randint(5, size=2)
for i in randomRows:
  print(a[i,:])

Selecting two arrays from the 2D array
[1 2 4 5 6]
[1 2 4 5 6]


## 6.0 Selecting Random Samples from a Dataset

In [ ]:
# Example 1
# ---
# Selecting a random sample from the following medical appointments dataset
# ---
# Dataset url = http://bit.ly/MedicalAppointmentsDataset
# ---
# 

# Loading the dataset
medical_df = pd.read_csv("http://bit.ly/MedicalAppointmentsDataset")

# Determining the size
print(medical_df.shape)


# Previewing the dataset
print(medical_df.head())

# Selecting the sample 
medical_sample = medical_df.sample(n = 10, replace="False")
print(medical_sample)

In [ ]:
medical_df = pd.read_csv("http://bit.ly/MedicalAppointmentsDataset")
medical_df.head(3)

PatientId  AppointmentID Gender  ... Handcap SMS_received  No-show
0  2.987250e+13        5642903      F  ...       0            0       No
1  5.589978e+14        5642503      M  ...       0            0       No
2  4.262962e+12        5642549      F  ...       0            0       No

[3 rows x 14 columns]

In [ ]:
# Determining the size
print(medical_df.shape)

(110527, 14)


In [ ]:
# Previewing the dataset
print(medical_df.head())

      PatientId  AppointmentID Gender  ... Handcap SMS_received  No-show
0  2.987250e+13        5642903      F  ...       0            0       No
1  5.589978e+14        5642503      M  ...       0            0       No
2  4.262962e+12        5642549      F  ...       0            0       No
3  8.679512e+11        5642828      F  ...       0            0       No
4  8.841186e+12        5642494      F  ...       0            0       No

[5 rows x 14 columns]


In [ ]:
# Selecting the sample 
medical_sample = medical_df.sample(n = 10, replace="False")
print(medical_sample)

          PatientId  AppointmentID Gender  ... Handcap SMS_received  No-show
25574  5.883369e+14        5684538      M  ...       0            1       No
43193  3.476624e+10        5692753      M  ...       0            0      Yes
2754   6.597319e+12        5516717      M  ...       0            1      Yes
76437  7.434455e+14        5655751      F  ...       0            0       No
64384  2.145389e+13        5687858      F  ...       0            0       No
82893  7.424723e+14        5594272      F  ...       0            0      Yes
43013  4.111860e+14        5528668      F  ...       0            0      Yes
15877  2.616696e+12        5684378      F  ...       0            0      Yes
1541   3.979298e+11        5641196      F  ...       0            0      Yes
14191  1.845411e+14        5754070      M  ...       0            0       No

[10 rows x 14 columns]


### <font color="green">6.0 Challenges </font>

In [ ]:
# Challenge 1
# ---
# Select a random sample of 10 from the given dataset below 
# ---
# Dataset url = http://bit.ly/DSRussianInvestigation

In [ ]:
# Loading the dataset
Russian_df = pd.read_csv("http://bit.ly/DSRussianInvestigation")
Russian_df.head(5)

investigation investigation-start  ... american      president
0     watergate          1973-05-19  ...     True  Richard Nixon
1     watergate          1973-05-19  ...     True  Richard Nixon
2     watergate          1973-05-19  ...     True  Richard Nixon
3     watergate          1973-05-19  ...     True  Richard Nixon
4     watergate          1973-05-19  ...     True  Richard Nixon

[5 rows x 13 columns]

In [ ]:
# Determining the size
print(Russian_df.shape)

(194, 13)


In [ ]:
# Previewing the dataset
print(Russian_df.head())

  investigation investigation-start  ... american      president
0     watergate          1973-05-19  ...     True  Richard Nixon
1     watergate          1973-05-19  ...     True  Richard Nixon
2     watergate          1973-05-19  ...     True  Richard Nixon
3     watergate          1973-05-19  ...     True  Richard Nixon
4     watergate          1973-05-19  ...     True  Richard Nixon

[5 rows x 13 columns]


In [ ]:
# Selecting the sample 

Russian_Investigation = Russian_df.sample(n = 10, replace = "False")
print(Russian_Investigation)


    investigation investigation-start  ... american         president
84    iran-contra          1986-12-19  ...     True     Ronald Reagan
87    iran-contra          1986-12-19  ...     True     Ronald Reagan
39      watergate          1973-05-19  ...     True     Richard Nixon
80    iran-contra          1986-12-19  ...     True     Ronald Reagan
183        russia          2017-05-17  ...    False      Donald Trump
50      watergate          1973-05-19  ...     True     Richard Nixon
83    iran-contra          1986-12-19  ...     True     Ronald Reagan
112        pierce          1990-03-01  ...     True  George H.W. Bush
53      watergate          1973-05-19  ...     True     Richard Nixon
99         pierce          1990-03-01  ...     True  George H.W. Bush

[10 rows x 13 columns]


In [ ]:
# Challenge 2
# ---
# A medical company would like to follow up with 50 patients who never showed up for appointments 
# but received an sms. Select a random sample from such patients given the medical dataset below 
# ---
# Dataset url = http://bit.ly/MedicalAppointmentsDataset

Appointments = pd.read_csv("http://bit.ly/MedicalAppointmentsDataset")
Appointments.head(3)

PatientId  AppointmentID Gender  ... Handcap SMS_received  No-show
0  2.987250e+13        5642903      F  ...       0            0       No
1  5.589978e+14        5642503      M  ...       0            0       No
2  4.262962e+12        5642549      F  ...       0            0       No

[3 rows x 14 columns]

In [ ]:
# Determining the size
print(Appointments.shape)

(110527, 14)


In [ ]:
# Previewing the dataset
print(Appointments.head())

      PatientId  AppointmentID Gender  ... Handcap SMS_received  No-show
0  2.987250e+13        5642903      F  ...       0            0       No
1  5.589978e+14        5642503      M  ...       0            0       No
2  4.262962e+12        5642549      F  ...       0            0       No
3  8.679512e+11        5642828      F  ...       0            0       No
4  8.841186e+12        5642494      F  ...       0            0       No

[5 rows x 14 columns]


In [ ]:
# Finding the sample

Medical_Appointments = Appointments.sample(n = 50, replace = "False")
Medical_Appointments

PatientId  AppointmentID Gender  ... Handcap SMS_received  No-show
89425   4.912537e+13        5779653      M  ...       0            0       No
98004   6.668787e+13        5645966      F  ...       0            1       No
33978   1.484611e+13        5635244      F  ...       0            1       No
21998   8.644573e+14        5709306      F  ...       0            0       No
99068   8.765746e+14        5770123      F  ...       0            1       No
44407   2.153462e+13        5639991      F  ...       0            0      Yes
52241   2.141687e+13        5708529      M  ...       0            0       No
26512   8.231720e+12        5664364      F  ...       0            0       No
32470   9.458741e+14        5598194      F  ...       0            1       No
18826   1.819924e+13        5703880      F  ...       0            0      Yes
81517   3.891146e+13        5603263      F  ...       0            1       No
32446   6.827596e+13        5682315      F  ...       0            0       No
84634   5.355689e+13        5761430      F  ...       0            0       No
56179   5.714997e+14        5712897      F  ...       0            0       No
66805   2.714365e+14        5671550      M  ...       0            0       No
48329   4.323282e+14        5632286      F  ...       0            0       No
42571   8.611562e+14        5706226      F  ...       0            1       No
44054   4.887834e+14        5667850      M  ...       0            0       No
86668   3.723555e+14        5750573      F  ...       0            1       No
2       4.262962e+12        5642549      F  ...       0            0       No
47823   4.944228e+11        5661954      M  ...       0            0       No
74230   2.685859e+13        5668339      F  ...       0            0       No
63798   1.231725e+11        5670400      M  ...       0            0       No
78787   1.626932e+14        5602487      F  ...       0            1       No
81409   7.232866e+13        5751196      M  ...       0            0       No
104417  9.366588e+14        5779537      M  ...       0            0       No
51824   7.427843e+14        5717335      M  ...       0            0      Yes
10135   3.965613e+12        5719717      F  ...       0            0       No
24330   1.893995e+13        5592268      M  ...       0            1       No
17548   3.922749e+12        5723581      F  ...       0            0       No
21358   3.491332e+13        5739046      F  ...       0            1       No
71036   8.458184e+13        5667710      M  ...       0            0       No
64347   4.139345e+12        5687796      F  ...       0            0      Yes
99952   2.963966e+11        5735968      F  ...       0            1       No
31592   1.315567e+14        5540451      F  ...       0            1      Yes
72045   6.986486e+12        5695630      F  ...       0            0       No
106496  5.464824e+14        5762694      F  ...       0            0       No
54825   6.999114e+12        5625743      F  ...       0            1       No
30382   5.149657e+12        5563201      F  ...       0            1       No
9829    1.551827e+13        5661035      F  ...       0            0       No
72157   3.694111e+12        5658400      M  ...       0            0       No
86748   3.362583e+12        5783746      F  ...       0            0       No
60640   6.534486e+13        5694042      M  ...       0            0       No
92806   9.792126e+13        5765032      F  ...       0            1      Yes
26309   9.367946e+13        5670787      M  ...       0            1       No
61193   7.373846e+13        5651782      F  ...       0            0      Yes
41315   6.695248e+13        5518762      F  ...       0            1       No
77360   3.956229e+13        5662380      F  ...       0            0      Yes
60858   4.415275e+13        5699309      M  ...       2            0       No
6457    5.243277e+12        5665318      M  ...       0            0       No

[50 rows x 14 columns]

In [ ]:
Medical_Appointments = Appointments.sample(n = 50, replace = "False")
print(Medical_Appointments)

           PatientId  AppointmentID Gender  ... Handcap SMS_received  No-show
108858  8.131241e+13        5771872      F  ...       0            0       No
9740    2.634855e+13        5722719      M  ...       0            0       No
15607   6.165972e+13        5621761      F  ...       0            0       No
104489  1.779894e+13        5755980      F  ...       0            0      Yes
28221   6.859188e+13        5653313      M  ...       0            0       No
47370   2.925556e+12        5530818      F  ...       0            1       No
66990   4.572634e+11        5632800      M  ...       0            0       No
71758   2.336118e+12        5726133      F  ...       0            0       No
97595   1.958650e+14        5764230      F  ...       0            0       No
53002   6.846545e+13        5686051      F  ...       0            0       No
101231  6.897527e+13        5665998      F  ...       0            1       No
78531   9.518185e+13        5732530      M  ...       0         